name: Grype scan via GHA

on:
    push:
     branches:
      - main
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # - name: Create empty JSON file in workspace
      #   run: |
      #     FILE_PATH="$GITHUB_WORKSPACE/store/request/request.json"
      #     mkdir -p "$(dirname "$FILE_PATH")"
      #     touch "$FILE_PATH"
      #     echo "File created at: $FILE_PATH"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t vulnerable-python-app .

      # Step 4: Save the Docker image as a TAR file
      - name: Save Docker image as TAR file
        run: |
          docker save -o output.tar vulnerable-python-app
          tar -tf output.tar
          
      - id: grype-step
        name: Grype scan
        uses: cloudbees-io-gha/trivy-scan-publish@v2
        with:
          binary-tar-path: output.tar
          cloudbees-url: https://api.saas-qa.beescloud.com
         

      # - name: Grype scan
      #   uses: cloudbees-io-gha/grype-scan-publish@v1
      #   with:
      #     binary-tar-path: debian.tar
      #     cloudbees-url: https://api.saas-qa.beescloud.com
         
          
          
         
